### PR TITLE
feat(scripts): add test script to launch datasource and grafana container

### LINKED ISSUE #5: [Task] Add simple script to launch datasource and grafana
Right now, it is quite hard to figure out what steps to follow to launch a working pair of datasource and grafana.

### PR DESCRIPTION
**Pull request by tthvo**
Closes #5 

A script is added to launch datasource and grafana containers. 

It is not recommended to run two processes locally as grafana-server likely runs into permission issues. With this way, it is closer to how these 2 containers are deployed in k8s/oc.

### CODE REVIEW

**Comment by tthvo** [comment]
Note that if you launch the script with `clean` argument, clean up process will be done.

**Comment by maxcao13** [comment]
If I just run the script as is, I get this error, is there something I'm missing?

```bash
❯ sh ./scripts/datasource_grafana_test.sh
[INFO] Creating pod cryostat-pod
0ced918031880668af5f5fded2a875bf6c5511d98ba99258504bd67ea80d45e1
[INFO] Creating datasource container with quay.io/cryostat/jfr-datasource:2.2.0-dev 
Trying to pull quay.io/cryostat/jfr-datasource:2.2.0-dev...
Error: initializing source docker://quay.io/cryostat/jfr-datasource:2.2.0-dev: reading manifest 2.2.0-dev in quay.io/cryostat/jfr-datasource: manifest unknown: manifest unknown
[INFO] Creating grafana container with quay.io/cryostat/cryostat-grafana-dashboard:2.2.0-dev 
Trying to pull quay.io/cryostat/cryostat-grafana-dashboard:2.2.0-dev...
Error: initializing source docker://quay.io/cryostat/cryostat-grafana-dashboard:2.2.0-dev: reading manifest 2.2.0-dev in quay.io/cryostat/cryostat-grafana-dashboard: manifest unknown: manifest unknown
```

**Comment by tthvo** [comment]
> If I just run the script as is, I get this error, is there something I'm missing?
> 
> ```shell
> ❯ sh ./scripts/datasource_grafana_test.sh
> [INFO] Creating pod cryostat-pod
> 0ced918031880668af5f5fded2a875bf6c5511d98ba99258504bd67ea80d45e1
> [INFO] Creating datasource container with quay.io/cryostat/jfr-datasource:2.2.0-dev 
> Trying to pull quay.io/cryostat/jfr-datasource:2.2.0-dev...
> Error: initializing source docker://quay.io/cryostat/jfr-datasource:2.2.0-dev: reading manifest 2.2.0-dev in quay.io/cryostat/jfr-datasource: manifest unknown: manifest unknown
> [INFO] Creating grafana container with quay.io/cryostat/cryostat-grafana-dashboard:2.2.0-dev 
> Trying to pull quay.io/cryostat/cryostat-grafana-dashboard:2.2.0-dev...
> Error: initializing source docker://quay.io/cryostat/cryostat-grafana-dashboard:2.2.0-dev: reading manifest 2.2.0-dev in quay.io/cryostat/cryostat-grafana-dashboard: manifest unknown: manifest unknown
> ```

Ahh maybe because I disabled pull `Always` so it might just grab from local registry. Let me fix.

**Comment by tthvo** [comment]
@maxcao13 It looks like `podman pull` failed due to unknown tags. There is no tag `2.2.0-dev`. Could you try just latest?

https://quay.io/repository/cryostat/jfr-datasource?tab=tags

**Comment by tthvo** [comment]
> Ahh maybe because I disabled pull Always so it might just grab from local registry. Let me fix.

I actually removed `Always` so that whenever you build the image for testing, it will take from your local registry, if not, then pulling from quay.io.

**Comment by maxcao13** [comment]
Mmm, my .bashrc env variables override `$IMAGE_VERSION`, that's why.

**Comment by tthvo** [comment]
Nicee! Any changes? :D

**Comment by maxcao13** [comment]
I'm not quite familar with bash scripts in general so what's the difference between
```
IMAGE_VERSION="latest"
```
and 
```
IMAGE_VERSION=${IMAGE_VERSION:-"latest"}
```
?

**Comment by tthvo** [comment]
> I'm not quite familar with bash scripts in general so what's the difference between
> 
> ```
> IMAGE_VERSION="latest"
> ```
> 
> and
> 
> ```
> IMAGE_VERSION=${IMAGE_VERSION:-"latest"}
> ```
> 
> ?

Ah this is part of [parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html). 

In this case, `:-` operator checks if the variable is unset or null (i.e. empty):
- If not, it is as it is set.
- If true (unset or null), then it will take the value following `:-`.

**Comment by maxcao13** [comment]
Ah, so that's why it takes precedence then. Would it make more sense to rename this env variable to something like `LOCAL_IMAGE_VERSION` since in the other docs, we write `export `IMAGE_VERSION``?

What do you think?

Also unrelated, but it seems when there is an error with the creating the first container `runJfrDatasource`, it doesn't stop the script but also runs the second container as well, and hence it will try to kill the pod twice. 
```
❯ sh ./scripts/datasource_grafana_test.sh 
[INFO] Creating pod cryostat-pod
ab3938e26a3f351ccd907f86c0b70e7f139fe4739bad713f4c10ba5378f48c02
[INFO] Creating datasource container with quay.io/cryostat/jfr-datasource:latestdfg 
Trying to pull quay.io/cryostat/jfr-datasource:latestdfg...
Error: initializing source docker://quay.io/cryostat/jfr-datasource:latestdfg: reading manifest latestdfg in quay.io/cryostat/jfr-datasource: manifest unknown: manifest unknown
ab3938e26a3f351ccd907f86c0b70e7f139fe4739bad713f4c10ba5378f48c02
ab3938e26a3f351ccd907f86c0b70e7f139fe4739bad713f4c10ba5378f48c02
[INFO] Creating grafana container with quay.io/cryostat/cryostat-grafana-dashboard:latestdfg 
Trying to pull quay.io/cryostat/cryostat-grafana-dashboard:latestdfg...
Error: initializing source docker://quay.io/cryostat/cryostat-grafana-dashboard:latestdfg: reading manifest latestdfg in quay.io/cryostat/cryostat-grafana-dashboard: manifest unknown: manifest unknown
Error: no pod with name or ID cryostat-pod found: no such pod
Error: no pod with name or ID cryostat-pod found: no such pod
```

**Comment by tthvo** [comment]
> rename this env variable to something like LOCAL_IMAGE_VERSION since in the other docs, we write export IMAGE_VERSION=2.2.0-dev?

Sound good! Will do that!

**Comment by tthvo** [comment]
> Also unrelated, but it seems when there is an error with the creating the first container runJfrDatasource, it doesn't stop the script but also runs the second container as well, and hence it will try to kill the pod twice.

Look like the handler should clean up and just exit! Fix now :D

**Comment by tthvo** [comment]
All fixed! Thanks for noticing that!

**Comment by maxcao13** [comment]
Everything looks good! I assume there will be some documentation eventually about what this script is for and how it works etc. right?

**Review by maxcao13 — APPROVED** [review]

**Comment by tthvo** [comment]
yess there should be a README for these soon! You can merge now :D

**Comment by maxcao13** [comment]
Thanks a lot! This is especially helpful to me ^^

**Pull request merged**
